name: Build and Release

on:
  push:
    tags:
      - 'v*'

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Build Release
        run: cargo build --release
      - name: Setup Inno Setup
        uses: Minionguyjpro/InnoSetup-Action@v1
      - name: Create Installer
        run: |
          iscc SleepTimerInstaller.iss
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SleepTimerInstaller.exe
          path: SleepTimerInstaller.exe

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install Rust
        uses: dtolnay/rust-toolchain@stable
      - name: Install cargo-appimage
        run: cargo install cargo-appimage
      - name: Build AppImage
        run: cargo appimage
      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: SleepTimer-x86_64.AppImage
          path: target/appimage/SleepTimer-*.AppImage

  release:
    needs: [build-windows, build-linux]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: SleepTimerInstaller.exe
          path: ./artifacts
      - uses: actions/download-artifact@v4
        with:
          name: SleepTimer-x86_64.AppImage
          path: ./artifacts
      - uses: ncipollo/release-action@v1
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            ./artifacts/SleepTimerInstaller.exe
            ./artifacts/SleepTimer-x86_64.AppImage
